- app/config/FrontendAppConfig.scala
- app/views/MainTemplate.scala.html
- conf/application.conf
Change to the get help with this page component
> DL-4081 Change to get help with this page

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- app/views/DisclaimerView.scala.html
- conf/messages.en
- Updated disclaimer page content to fit the prototype
- Updated README
- Added PR template
> DL-4106 Updating disclaimer page content to fit prototype

- app/controllers/SubmitYourClaimController.scala
- app/views/SubmitYourClaimView.scala.html
- conf/app.routes
- conf/messages.en
- migrations/applied_migrations/SubmitYourClaim.sh
- test/controllers/SubmitYourClaimControllerSpec.scala
- test/views/SubmitYourClaimViewSpec.scala
Introduced a new page based on sprint 25 https://employee-expenses.herokuapp.com/working-from-home/sprint-25/declaration-end. This page is to appear after the page that shows your tax relief and before the successfully submitted page.
*Reviewee* (@grahampaulcook )
> DL-4109 Declaration end/pre submission page

- app/connectors/TaiConnector.scala
- app/models/ETag.scala
- test/connectors/TaiConnectorSpec.scala
> DL-4139 Adding functionality for IABD 59 POST request

- app/config/FrontendAppConfig.scala
- app/connectors/PaperlessPreferenceConnector.scala
- conf/application.conf
- project/AppDependencies.scala
- test/base/SpecBase.scala
- test/connectors/PaperlessConnectorSpec.scala
> DL-4141 - Added Paperless Pref. connector

- app/assets/javascripts/gtm.js
- app/config/FrontendAppConfig.scala
- app/views/MainTemplate.scala.html
- conf/application.conf
Added GTM support based on https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=149685805
*Reviewee* (@grahampaulcook )
> DL-4258 GTM added

- app/config/FrontendAppConfig.scala
- app/connectors/PaperlessPreferenceConnector.scala
- app/controllers/ConfirmationController.scala
- app/views/ConfirmationView.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- test/base/SpecBase.scala
- test/connectors/CitizenDetailsConnectorSpec.scala
- test/controllers/ConfirmationControllerSpec.scala
- test/views/ConfirmationViewSpec.scala
> DL-4224 - Confirmation Page enhancements

- app/config/Module.scala
- app/controllers/CannotClaimUsingThisServiceController.scala
- app/controllers/ConfirmationController.scala
- app/controllers/DisclaimerController.scala
- app/controllers/WhenDidYouFirstStartWorkingFromHomeController.scala
- app/controllers/YourTaxReliefController.scala
- app/controllers/actions/ManualCorrespondenceIndicatorAction.scala
- test/base/SpecBase.scala
- test/controllers/actions/FakeManualCorrespondenceIndicatorAction.scala
- test/controllers/actions/ManualCorrespondenceIndicatorActionSpec.scala
All GET/POST's of the service will check for a Manual Correspondence Indicator on the user's citizen details record. If there is an MCI set then the user will be redirected to the MCI controller and view.
*Reviewee* (@grahampaulcook)
> DL-4257 Citizen details MCI check

- app/controllers/ConfirmationController.scala
- test/controllers/ConfirmationControllerSpec.scala
> DL-4271 - Added auditing to paperless lookup

- app/connectors/TaiConnector.scala
- test/connectors/TaiConnectorSpec.scala
Minor change to the end point URL for POST'ing IABD 59 data.
> DL-4291 Change to TAI POST url

- app/assets/stylesheets/employeewfhexpensesfrontend-app.scss
- app/config/FrontendAppConfig.scala
- app/controllers/KeepAliveController.scala
- app/controllers/SignedOutController.scala
- app/views/MainTemplate.scala.html
- app/views/WeSignedYouOutPageView.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- test/controllers/KeepAliveControllerSpec.scala
- test/controllers/SignedOutControllerSpec.scala
- test/views/SignedOutViewSpec.scala
> DL-4105 - Implement the service timeout

- app/controllers/SignedOutController.scala
- app/views/MainTemplate.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- project/AppDependencies.scala
Accessibility statement added into footer + sign out link which redirects to the exit survey.
> DL-4166 Accessibility and sign out to survey

- app/controllers/SignedOutController.scala
- app/views/MainTemplate.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- project/AppDependencies.scala
Reverts hmrc/employee-wfh-expenses-frontend#30
> Revert "DL-4166 Accessibility and sign out to survey"

- conf/application-json-logger.xml
**Bug fix**
Allows **uk.gov** and **application** logback levels to be configurable via app-config
> Configurable logback level

- app/views/ErrorTemplate.scala.html
> DL-4305 Fixing error page

- app/views/MainTemplate.scala.html
> DL-4303 - Fixed javascript 404 issue

- app/config/FrontendAppConfig.scala
- app/controllers/UnauthorisedController.scala
- app/views/IdentityVerificationFailedView.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- test/controllers/UnauthorisedControllerSpec.scala
- test/controllers/actions/AuthActionSpec.scala
- test/views/IdentityVerificationFailedViewSpec.scala
**Bug fix**
Identity verification content changes
> DL-4308 IV Failed content

- app/services/SubmissionService.scala
- app/views/YourTaxRelief2019And2020View.scala.html
- app/views/YourTaxRelief2020OnlyView.scala.html
**Bug fix**
Prevent double clicking on the submit button.
> DL-4314 Prevent double clicking on the submit button

- app/controllers/DisclaimerController.scala
> DL-4437 Defer check for already claimed

- app/controllers/WhenDidYouFirstStartWorkingFromHomeController.scala
> DL-4437 Remove `checkAlreadyClaimed` from POST

- app/controllers/TechnicalDifficultiesController.scala
> DL-4460 Tech error page to be 500 not 200 http response

- app/config/FrontendAppConfig.scala
- app/views/MainTemplate.scala.html
- conf/application.conf
Added the Optimizely script to HEAD of main template view
*Reviewee* (@grahampaulcook )
> DL-4677 Adding Optimizely script to HEAD

- app/views/ConfirmationView.scala.html
> DL-4978 - added spacing and increase text size for paperless

- README.md
- app/config/FrontendAppConfig.scala
- app/config/Module.scala
- app/config/RateLimitConfig.scala
- app/controllers/actions/CheckAlreadyClaimedAction.scala
- app/controllers/actions/IdentifierAction.scala
- app/handlers/ErrorHandler.scala
- app/services/IABDService.scala
- app/services/SubmissionService.scala
- app/utils/RateLimiting.scala
- conf/application.conf
- conf/messages
- project/AppDependencies.scala
- test/controllers/actions/AuthActionSpec.scala
- test/services/IABDServiceImplSpec.scala
- test/services/SubmissionServiceSpec.scala
- test/utils/RateLimitingSpec.scala
Rate limiting feature for IABD GET's and POST's
*Reviewee* (@grahampaulcook)
> DL-4979 Rate limit on IABD GET's and POST's

- app/views/Disclaimer2019_2020View.scala.html
- app/views/Disclaimer2019_2020_2021View.scala.html
- app/views/Disclaimer2021View.scala.html
- conf/messages
- conf/messages.cy
> DL-4985 Disclaimer content added

- app/assets/javascripts/gtm.js
- app/views/CannotClaimUsingThisServiceView.scala.html
- app/views/ConfirmationView.scala.html
- app/views/ErrorTemplate.scala.html
- app/views/IdentityVerificationFailedView.scala.html
- app/views/IndexView.scala.html
- app/views/MainTemplate.scala.html
- app/views/ManualCorrespondenceIndicatorView.scala.html
- app/views/SessionExpiredView.scala.html
- app/views/TechnicalErrorView.scala.html
- app/views/UnauthorisedView.scala.html
- app/views/WeSignedYouOutPageView.scala.html
- conf/application.conf
- project/AppDependencies.scala
- test/controllers/CannotClaimUsingThisServiceControllerSpec.scala
- test/controllers/ConfirmationControllerSpec.scala
- test/controllers/ManualCorrespondenceIndicatorControllerSpec.scala
- test/controllers/SessionExpiredControllerSpec.scala
- test/controllers/SignedOutControllerSpec.scala
- test/controllers/UnauthorisedControllerSpec.scala
- test/views/CannotClaimUsingThisServiceViewSpec.scala
- test/views/ConfirmationViewSpec.scala
- test/views/IdentityVerificationFailedViewSpec.scala
- test/views/IndexViewSpec.scala
- test/views/ManualCorrespondenceIndicatorViewSpec.scala
- test/views/SessionExpiredViewSpec.scala
- test/views/SignedOutViewSpec.scala
- test/views/UnauthorisedViewSpec.scala
> DL-5020 Integrate tracking consent

- conf/messages
> DL-4973 Content update

- app/forms/WhenDidYouFirstStartWorkingFromHomeFormProvider.scala
- app/forms/mappings/LocalDateFormatter.scala
- app/forms/mappings/Mappings.scala
- conf/messages
- conf/messages.cy
- test/forms/mappings/DateMappingsSpec.scala
> DL-5159 Adding validation to start date field

- app/config/FrontendAppConfig.scala
- app/controllers/YourTaxReliefController.scala
- app/models/UserAnswers.scala
- app/services/SubmissionService.scala
- conf/application.conf
- test/services/SubmissionServiceSpec.scala
DL-4977 - Adding submission logic for 2021/22 claim cases
> DL-4977 - Adding submission logic for 2021/22 claim cases

- conf/app.routes
> DL-4973 Correcting route for selectTaxYearsToClaimFor page

- app/views/MainTemplate.scala.html
> DL-5184 Footer links

- project/AppDependencies.scala
- test/controllers/SelectTaxYearsToClaimForControllerSpec.scala
> DL-5187 Dependency changes

- app/views/MainTemplate.scala.html
> DL-5188 A11y alert fix within the header

- app/views/Disclaimer2019_2020View.scala.html
- app/views/Disclaimer2019_2020_2021View.scala.html
- app/views/Disclaimer2021View.scala.html
- conf/messages
- conf/messages.cy
> DL-4985 Disclaimer content small fixes

- app/controllers/YourTaxReliefController.scala
- app/controllers/actions/DataRequiredAction.scala
- app/pages/SubmittedClaim.scala
- app/services/SubmissionService.scala
- test/controllers/actions/DataRequiredActionSpec.scala
- test/services/SubmissionServiceSpec.scala
> DL-5198 Submitted status handling

- app/views/YourTaxRelief2019_2020View.scala.html
- app/views/YourTaxRelief2019_2020_2021View.scala.html
> DL-4986 Full stop after date added to tax relief page

- conf/messages
- conf/messages.cy
DL-5134
Welsh content for all phase 2 work added
> DL-5134 Phase 2 Welsh translations added

- app/controllers/ConfirmationController.scala
- app/controllers/actions/CheckAlreadyClaimedAction.scala
- app/controllers/actions/IdentifierAction.scala
- app/controllers/actions/ManualCorrespondenceIndicatorAction.scala
- app/handlers/ErrorHandler.scala
- app/navigation/Navigator.scala
- app/services/SubmissionService.scala
- app/views/Confirmation2019_2020View.scala.html
- app/views/Confirmation2019_2020_2021View.scala.html
- app/views/Confirmation2021View.scala.html
- conf/application.conf
- project/AppDependencies.scala
- test/controllers/WhenDidYouFirstStartWorkingFromHomeControllerSpec.scala
- test/resources/test.application.conf
- test/services/SubmissionServiceSpec.scala
> DL-5422 Bootstrap 4 dependency update

- conf/application.conf
> DL-5422 Content Security Policy changes for Play 2.7

- app/views/Confirmation2019_2020View.scala.html
- app/views/Confirmation2019_2020_2021View.scala.html
- app/views/Confirmation2021View.scala.html
- build.sbt
- project/plugins.sbt
> DL-5528 Feedback link to open in new tab

- app/connectors/PaperlessPreferenceConnector.scala
- project/AppDependencies.scala
- project/plugins.sbt
> DL-5456 Auth-client upgrade

- .gitignore
- app/controllers/actions/ManualCorrespondenceIndicatorAction.scala
- app/handlers/ErrorHandler.scala
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/connectors/PaperlessConnectorSpec.scala
- test/controllers/SignedOutControllerSpec.scala
- test/controllers/WhenDidYouFirstStartWorkingFromHomeControllerSpec.scala
- test/controllers/actions/DataRequiredActionSpec.scala
- test/services/IABDServiceImplSpec.scala
- test/services/SubmissionServiceSpec.scala
- test/services/TaxYearDatesSpec.scala
- test/utils/RateLimitingSpec.scala
> DL-5738 Play 2.8 upgrade

- app/models/paperless/PaperlessStatusResponse.scala
- test/controllers/ConfirmationControllerSpec.scala
*Stephen* (Replace with your name)
> DL-6748 - Removed text and category from paperless JSON

- app/config/FrontendAppConfig.scala
- app/views/MainTemplate.scala.html
- conf/application.conf
- conf/messages
- conf/messages.cy
> DL-6717 - added beta feedback

- app/config/FrontendAppConfig.scala
- conf/application.conf
> DL-6717 changed config for beta banner

- app/config/FrontendAppConfig.scala
- app/connectors/EligibilityCheckerConnector.scala
- app/controllers/IndexController.scala
- app/controllers/SelectTaxYearsToClaimForController.scala
- app/models/UserAnswers.scala
- app/models/WfhDueToCovidStatusWrapper.scala
- app/pages/EligibilityCheckerSessionId.scala
- app/services/EligibilityCheckerService.scala
- conf/application.conf
- test/controllers/SelectTaxYearsToClaimForControllerSpec.scala
- test/services/EligibilityCheckerServiceSpec.scala
- [-]  I've run a dependency check to ensure all dependencies are up to date
> DL-6639 - SA check replacement

- app/models/SelectTaxYearsToClaimFor.scala
- conf/messages
> DL-6904 Added new 2022/23 checkbox option

- app/controllers/DisclaimerController.scala
- app/controllers/SelectTaxYearsToClaimForController.scala
- app/controllers/WhenDidYouFirstStartWorkingFromHomeController.scala
- app/controllers/YourTaxReliefController.scala
- app/navigation/Navigator.scala
- app/navigation/SelectedTaxYears.scala
> Dl 6202 disclaimer v2

- app/controllers/DisclaimerController.scala
- app/controllers/IndexController.scala
- app/controllers/SelectTaxYearsToClaimForController.scala
- app/controllers/actions/CheckAlreadyClaimedAction.scala
- app/models/SelectTaxYearsToClaimFor.scala
- app/navigation/Navigator.scala
- app/pages/ClaimedForTaxYear2021.scala
- app/pages/ClaimedForTaxYear2022.scala
- app/views/SelectTaxYearsToClaimForView.scala.html
- test/controllers/IndexControllerSpec.scala
- test/controllers/SelectTaxYearsToClaimForControllerSpec.scala
- test/forms/SelectTaxYearsToClaimForFormProviderSpec.scala
- test/models/SelectTaxYearsToClaimForSpec.scala
- test/views/SelectTaxYearsToClaimForViewSpec.scala
DL-6907
TAI lookup upon loading up the service
Note: the TAI calls are currently being duplicated in the CheckAlreadyClaimedAction and IndexController - looking into a way to stop this, but merging this branch to push and test in pre-prod
> Dl 6907 v2

- app/controllers/DisclaimerController.scala
- app/views/DisclaimerView.scala.html
- app/views/SelectTaxYearsToClaimForView.scala.html
- app/views/YourTaxReliefView.scala.html
- test/controllers/DisclaimerControllerSpec.scala
- test/views/SelectTaxYearsToClaimForViewSpec.scala
> Adding back links to pages

- app/controllers/CheckYourClaimController.scala
- app/controllers/SelectTaxYearsToClaimForController.scala
- app/models/SelectTaxYearsToClaimFor.scala
- app/navigation/Navigator.scala
- test/controllers/IndexControllerSpec.scala
- test/controllers/SelectTaxYearsToClaimForControllerSpec.scala
> DL-7198 Redirecting to relevant page instead of showing single checkbox

- app/controllers/SelectTaxYearsToClaimForController.scala
> DL-7198 Re-adding in changes from DL-7198

- app/controllers/CheckYourClaimController.scala
- app/controllers/IndexController.scala
- app/controllers/YourTaxReliefController.scala
- test/controllers/IndexControllerSpec.scala
> P87 Kickout handled in IndexController

- app/config/FrontendAppConfig.scala
- app/controllers/IndexController.scala
- app/controllers/SelectTaxYearsToClaimForController.scala
- app/views/CannotClaimUsingThisServiceView.scala.html
- app/views/CheckYourClaimView.scala.html
- app/views/ConfirmationView.scala.html
- app/views/DisclaimerView.scala.html
- app/views/ErrorTemplate.scala.html
- app/views/IdentityVerificationFailedView.scala.html
- app/views/IndexView.scala.html
- app/views/ManualCorrespondenceIndicatorView.scala.html
- app/views/SelectTaxYearsToClaimForView.scala.html
- app/views/SessionExpiredView.scala.html
- app/views/TechnicalErrorView.scala.html
- app/views/UnauthorisedView.scala.html
- app/views/WeSignedYouOutPageView.scala.html
- app/views/WhenDidYouFirstStartWorkingFromHomeView.scala.html
- app/views/YourTaxReliefView.scala.html
- conf/application.conf
- test/controllers/SelectTaxYearsToClaimForControllerSpec.scala
> DL-7425 Further changes

- test/views/DisclaimerViewSpec.scala
- test/views/ViewSpecBase.scala
- test/views/behaviours/ViewBehaviours.scala
> Disclaimer page unit test fix

- app/controllers/CheckYourClaimController.scala
- app/controllers/ConfirmationController.scala
- app/controllers/DisclaimerController.scala
- app/controllers/WhenDidYouFirstStartWorkingFromHomeController.scala
- app/controllers/YourTaxReliefController.scala
- app/views/ConfirmationView.scala.html
- app/views/MainTemplate.scala.html
- test/controllers/ConfirmationControllerSpec.scala
> DL-7425 Don't allow users to jump ahead in journey via manual URL

- app/controllers/SelectTaxYearsToClaimForController.scala
> DL-7494 Fixing the form errors on selectTaxYearsToClaimFor

- app/views/SelectTaxYearsToClaimForView.scala.html
- conf/messages
Error summary now focuses on first checkbox.
*Stephen*
> DL-9301 - SelectTaxYearsToClaimForView

- app/forms/NumberOfWeeksToClaimForFormProvider.scala
- app/utils/TaxYearDates.scala
- app/views/NumberOfWeeksToClaimForView.scala.html
- conf/messages
- test/forms/NumberOfWeeksToClaimForFormProviderSpec.scala
- test/forms/behaviours/IntFieldBehaviours.scala
- test/views/NumberOfWeeksToClaimForViewSpec.scala
- test/views/behaviours/IntViewBehaviours.scala
- test/views/behaviours/QuestionViewBehaviours.scala
- test/views/behaviours/StringViewBehaviours.scala
- test/views/behaviours/YesNoViewBehaviours.scala
> DL-9297 - SelectTaxYearsToClaimForView

- app/views/InformClaimNowInWeeksView.scala.html
- conf/messages
- conf/messages.cy
- test/views/InformClaimNowInWeeksViewSpec.scala
> DL-9299 informClaimNowInWeeksView.scala

- app/views/CheckYourClaimView.scala.html
DL-9482
Updated the details component showing extra costs content to show regardless of years selected
> DL-9482 Updating details component on checkYourClaim to always show

- app/views/SelectTaxYearsToClaimForView.scala.html
> DL-9647 made hint text show for both journey's

- app/controllers/actions/IdentifierAction.scala
- test/base/SpecBase.scala
- test/controllers/actions/AuthActionSpec.scala
- test/controllers/actions/CheckAlreadyClaimedActionSpec.scala
- test/controllers/actions/DataRetrievalActionSpec.scala
- test/controllers/actions/FakeIdentifierAction.scala
- test/controllers/actions/ManualCorrespondenceIndicatorActionSpec.scala
- test/utils/RetrievalOps.scala
> DL-10175 Allowing Org credentials into the service

- app/views/MainTemplate.scala.html
- test/views/SignedOutViewSpec.scala
- test/views/behaviours/IntViewBehaviours.scala
- test/views/behaviours/QuestionViewBehaviours.scala
- test/views/behaviours/StringViewBehaviours.scala
- test/views/behaviours/ViewBehaviours.scala
- test/views/behaviours/YesNoViewBehaviours.scala
> DL-10418 - Amended page titles

- app/views/IdentityVerificationFailedView.scala.html
- app/views/UnauthorisedView.scala.html
- conf/messages
- conf/messages.cy
> DL-10152 - updated auth pages content

- project/AppDependencies.scala
- test/controllers/CannotClaimUsingThisServiceControllerSpec.scala
- test/controllers/CheckYourClaimControllerSpec.scala
- test/controllers/ConfirmClaimInWeeksControllerSpec.scala
- test/controllers/ConfirmationControllerSpec.scala
- test/controllers/DisclaimerControllerSpec.scala
- test/controllers/HowWeWillCalculateTaxReliefControllerSpec.scala
- test/controllers/ManualCorrespondenceIndicatorControllerSpec.scala
- test/controllers/SelectTaxYearsToClaimForControllerSpec.scala
- test/controllers/SessionExpiredControllerSpec.scala
- test/controllers/SignedOutControllerSpec.scala
- test/controllers/UnauthorisedControllerSpec.scala
- test/controllers/WhenDidYouFirstStartWorkingFromHomeControllerSpec.scala
> DL-10171 Dependency upgrades

- README.md
- app/config/FrontendAppConfig.scala
- app/config/Module.scala
- app/models/UserAnswers.scala
- app/repositories/SessionRepository.scala
- build.sbt
- conf/application.conf
- conf/logback.xml
- project/AppDependencies.scala
- run.sh
- test/controllers/CheckYourClaimControllerSpec.scala
- test/controllers/ConfirmClaimInWeeksControllerSpec.scala
- test/controllers/ConfirmationControllerSpec.scala
- test/controllers/IndexControllerSpec.scala
- test/controllers/SelectTaxYearsToClaimForControllerSpec.scala
- test/controllers/WhenDidYouFirstStartWorkingFromHomeControllerSpec.scala
- test/controllers/actions/AuthActionSpec.scala
- test/controllers/actions/CheckAlreadyClaimedActionSpec.scala
- test/repositories/SessionRepositorySpec.scala
- test/services/EligibilityCheckerServiceSpec.scala
- test/services/IABDServiceImplSpec.scala
- test/services/SubmissionServiceSpec.scala
Updated the mongo dependencies to use mongo-play, and updated tests.
*Reviewee* (Jacques Waugh)
> DL-10179 migrate from reactivemongo to mongo-play

- conf/messages
- conf/messages.cy
> DL-11322 updating CheckYourClaim page title

- conf/messages
- conf/messages.cy
> DL-11323 updating confirmation page title

- app/views/WhenDidYouFirstStartWorkingFromHomeView.scala.html
> DL-11320 - added fieldset to start date page

- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/views/behaviours/ViewBehaviours.scala
> DL-11770 - removed CSP directive

- project/AppDependencies.scala
> DL-12974 update crown logo

- app/config/FrontendAppConfig.scala
- app/controllers/ConfirmationController.scala
- app/models/ClaimStatus.scala
- app/models/TaxYearFromUIAssembler.scala
- app/views/ConfirmationMergeJourneyView.scala.html
- conf/messages
- conf/messages.cy
- test/controllers/ConfirmationControllerSpec.scala
- test/views/ConfirmationMergeJourneyViewSpec.scala
> DL-13034 merge journey summary page

- app/config/FrontendAppConfig.scala
- app/controllers/ConfirmationController.scala
- app/views/ConfirmationMergeJourneyView.scala.html
- conf/application.conf
- conf/messages
- conf/messages.cy
- test/views/ConfirmationMergeJourneyViewSpec.scala
> DL-13034-2 merge journey fixes and welsh

- app/controllers/ConfirmClaimInWeeksController.scala
- app/views/ConfirmClaimInWeeksView.scala.html
- conf/messages
- conf/messages.cy
- test/views/ConfirmClaimInWeeksViewSpec.scala
> DL-13355 confirm claim weeks page

- app/controllers/NumberOfWeeksToClaimForController.scala
- app/controllers/SelectTaxYearsToClaimForController.scala
- app/forms/NumberOfWeeksToClaimForFormProvider.scala
- app/views/HowWeWillCalculateTaxReliefView.scala.html
- app/views/NumberOfWeeksToClaimForMultipleYearsView.scala.html
- app/views/components/input_number.scala.html
- conf/messages
- conf/messages.cy
- test/controllers/NumberOfWeeksToClaimForControllerSpec.scala
- test/forms/NumberOfWeeksToClaimForFormProviderSpec.scala
- test/views/NumberOfWeeksToClaimForMultipleYearsViewSpec.scala
- test/views/behaviours/QuestionViewBehaviours.scala
DL-13356
- [ x]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
> DL-13356 Adding number of weeks input for multiple years

- app/controllers/ConfirmationController.scala
- app/views/ConfirmationView.scala.html
> DL-13132 confirmation page

- app/models/TaxYearSelection.scala
- test/controllers/CheckYourClaimControllerSpec.scala
- test/controllers/NumberOfWeeksToClaimForControllerSpec.scala
- test/services/IABDServiceSpec.scala
- test/services/SubmissionServiceSpec.scala
- test/views/CheckYourClaimViewSpec.scala
- test/views/HowWeWillCalculateTaxReliefPageViewSpec.scala
> DL-13509 - made unit tests dynamic and future proof

- project/AppDependencies.scala
- project/plugins.sbt
> DL-15073:Dependency Upgrades

- conf/application.conf
> DL-16800: Enabled GOV UK rebrand feature switch
